<?php
namespace Home\Controller;
use Think\Controller;
class ResumeSendController extends BaseController {
	public function index(){
		$this->display();
	}
	//所有发送的简历
	public function allSend(){
		//显示头部用户名
		$user=M('users');
		$id=session('user.id');
		$res_user=$user->where("id=$id")->find();
		if($res_user){
			$this->data['username']=$res_user['username'];
		}
		//投递职位的遍历
		//
		$send=M('send');
		$company=M('company');
		$job=M('job');
		$res_send=$send->where("user_id=$id")->select();
		if($res_send){
			foreach($res_send as $key=>$value){
				$arr=$value;
				//first
				if($value['state1']==1){
					$arr['state_1']='done';
				}else{
					$arr['state_1']='grey';
				}
				//second	
				if($value['state2']==1){
					$arr['state_2']='done';
				}else{
					$arr['state_2']='grey';
				}
				//third
				if($value['state3']==0){
					$arr['state_3']='grey';
					$arr['state_3_value']='被转发';
				}elseif($value['state3']==1){
					$arr['state_3']='done';
					$arr['state_3_value']='被转发';
				}else{
					$arr['state_3']='done';
					$arr['state_3_value']='通过初筛';
				}
				//fourth
				if($value['state4']==0){
					$arr['state_4']='grey';
					$arr['state_4_value']='通知面试';
				}elseif($value['state4']==1){
					$arr['state_4']='done';
					$arr['state_4_value']='通知面试';
				}else{
					$arr['state_4']='done';
					$arr['state_4_value']='不合适';
				}
				$res_job=$job->where("id={$arr['job_id']}")->find();
				if($res_job){
					$arr['job']=$res_job;
				}
				$res_company=$company->where("id={$arr['company_id']}")->find();
				if($res_company){
					$arr['company']=$res_company;
				}
				$result[]=$arr;
			}
		}
		//var_dump($result);
		//显示用户投递的职位
		$this->assign('data',$this->data);
		$this->assign('result',$result);
		$this->display('ResumeSend/index');	
	}
	//查看过的简历
	public function lookSuccess(){
		$user=M('users');
		$id=session('user.id');
		$res_user=$user->where("id=$id")->find();
		if($res_user){
			$this->data['username']=$res_user['username'];
		}
		//投递职位的遍历
		$send=M('send');
		$company=M('company');
		$job=M('job');
		$res_send=$send->where("user_id=$id")->select();
		if($res_send){
			foreach($res_send as $key=>$value){
				//second	
				if($value['state2']==1){
					$arr=$value;
					$arr['state_2']='done';
					//first
					if($value['state1']==1){
						$arr['state_1']='done';
					}else{
						$arr['state_1']='grey';
					}
					//third
					if($value['state3']==0){
						$arr['state_3']='grey';
						$arr['state_3_value']='被转发';
					}elseif($value['state3']==1){
						$arr['state_3']='done';
						$arr['state_3_value']='被转发';
					}else{
						$arr['state_3']='done';
						$arr['state_3_value']='通过初筛';
					}
					//fourth
					if($value['state4']==0){
						$arr['state_4']='grey';
						$arr['state_4_value']='通知面试';
					}elseif($value['state4']==1){
						$arr['state_4']='done';
						$arr['state_4_value']='通知面试';
					}else{
						$arr['state_4']='done';
						$arr['state_4_value']='不合适';
					}
					$res_job=$job->where("id={$arr['job_id']}")->find();
					if($res_job){
						$arr['job']=$res_job;
					}
					$res_company=$company->where("id={$arr['company_id']}")->find();
					if($res_company){
						$arr['company']=$res_company;
						$result[]=$arr;	
					}
				}			
			}
		}
		//var_dump($result);
		//var_dump($res_send);
		//显示用户投递的职位
		$this->assign('data',$this->data);
		$this->assign('result',$result);
		$this->display('ResumeSend/index');			
	}
	//被转发的简历
	public function resendSuccess(){
		$user=M('users');
		$id=session('user.id');
		$res_user=$user->where("id=$id")->find();
		if($res_user){
			$this->data['username']=$res_user['username'];
		}
		//投递职位的遍历
		$send=M('send');
		$company=M('company');
		$job=M('job');
		$res_send=$send->where("user_id=$id")->select();
		if($res_send){
			foreach($res_send as $key=>$value){
				//second	
				if($value['state3']==1){
					$arr=$value;
					$arr['state_3']='done';
					$arr['state_3_value']='被转发';
					//first
					if($value['state1']==1){
						$arr['state_1']='done';
					}else{
						$arr['state_1']='grey';
					}
					//second
					if($value['state2']==1){
						$arr['state_2']='done';
					}else{
						$arr['state_2']='grey';
					}
					//fourth
					if($value['state4']==0){
						$arr['state_4']='grey';
						$arr['state_4_value']='通知面试';
					}elseif($value['state4']==1){
						$arr['state_4']='done';
						$arr['state_4_value']='通知面试';
					}else{
						$arr['state_4']='done';
						$arr['state_4_value']='不合适';
					}
					$res_job=$job->where("id={$arr['job_id']}")->find();
					if($res_job){
						$arr['job']=$res_job;
					}
					$res_company=$company->where("id={$arr['company_id']}")->find();
					if($res_company){
						$arr['company']=$res_company;
						$result[]=$arr;	
					}
				}			
			}
		}
		var_dump($result);
		//var_dump($res_send);
		//显示用户投递的职位
		$this->assign('data',$this->data);
		$this->assign('result',$result);
		//$this->display('ResumeSend/index');			
	}
	//通知面试的简历
	public function noticeAudition(){
		$user=M('users');
		$id=session('user.id');
		$res_user=$user->where("id=$id")->find();
		if($res_user){
			$this->data['username']=$res_user['username'];
		}
		//投递职位的遍历
		$send=M('send');
		$company=M('company');
		$job=M('job');
		$res_send=$send->where("user_id=$id")->select();
		if($res_send){
			foreach($res_send as $key=>$value){
				//second	
				if($value['state4']==1){
					$arr=$value;
					$arr['state_4']='done';
					$arr['state_4_value']='通知面试';
					//first
					if($value['state1']==1){
						$arr['state_1']='done';
					}else{
						$arr['state_1']='grey';
					}
					//second
					if($value['state2']==1){
						$arr['state_2']='done';
					}else{
						$arr['state_2']='grey';
					}
					//third
					if($value['state3']==0){
						$arr['state_3']='grey';
						$arr['state_3_value']='被转发';
					}elseif($value['state3']==1){
						$arr['state_3']='done';
						$arr['state_3_value']='被转发';
					}else{
						$arr['state_3']='done';
						$arr['state_3_value']='通过初筛';
					}
					$res_job=$job->where("id={$arr['job_id']}")->find();
					if($res_job){
						$arr['job']=$res_job;
					}
					$res_company=$company->where("id={$arr['company_id']}")->find();
					if($res_company){
						$arr['company']=$res_company;
						$result[]=$arr;	
					}
				}			
			}
		}
		var_dump($result);
		//var_dump($res_send);
		//显示用户投递的职位
		$this->assign('data',$this->data);
		$this->assign('result',$result);
		//$this->display('ResumeSend/index');	
	}
	//不合格的简历
	public function notBy(){
		$user=M('users');
		$id=session('user.id');
		$res_user=$user->where("id=$id")->find();
		if($res_user){
			$this->data['username']=$res_user['username'];
		}
		//投递职位的遍历
		$send=M('send');
		$company=M('company');
		$job=M('job');
		$res_send=$send->where("user_id=$id")->select();
		if($res_send){
			foreach($res_send as $key=>$value){
				//second	
				if($value['state4']==2){
					$arr=$value;
					$arr['state_4']='done';
					$arr['state_4_value']='不合格';
					//first
					if($value['state1']==1){
						$arr['state_1']='done';
					}else{
						$arr['state_1']='grey';
					}
					//second
					if($value['state2']==1){
						$arr['state_2']='done';
					}else{
						$arr['state_2']='grey';
					}
					//third
					if($value['state3']==0){
						$arr['state_3']='grey';
						$arr['state_3_value']='被转发';
					}elseif($value['state3']==1){
						$arr['state_3']='done';
						$arr['state_3_value']='被转发';
					}else{
						$arr['state_3']='done';
						$arr['state_3_value']='通过初筛';
					}
					$res_job=$job->where("id={$arr['job_id']}")->find();
					if($res_job){
						$arr['job']=$res_job;
					}
					$res_company=$company->where("id={$arr['company_id']}")->find();
					if($res_company){
						$arr['company']=$res_company;
						$result[]=$arr;	
					}
				}			
			}		
	}
}